name:  Refrigeration-Cycle-Simulation

channels:
  - conda-forge

dependencies:
  - python
  - jupyter
  - jupyterlab
  - matplotlib
  - matplotlib-label-lines
  - numpy
  - csv
  - CoolProp
  - functools
  - matplotlib
  - typing


