name:  Refrigeration-Cycle-Simulation

channels:
  - conda-forge

dependencies:
  - python
  - jupyter
  - jupyterlab
  - matplotlib
  - numpy
  - csv
  - CoolProp
  - functools
  - labelines
  - matplotlib
  - typing


